data:
    data_root: /
    data_spreadsheet: spreadsheets/
    labels: ['idh', 'codel', 'atrx']
    train_centers: ['UM']
    transform_strength: strong # strong or weak
    image_size: 300
model:
    vision_backbone: resnet # resnet, inception, resnext, vit_s, vit_b, vit_l
    classifier: linear # linear or tran
    pretrained_vision_model: '' # path to pretrained vision model
    freeze_feature_extractor: False
    pretrain_embed: True # only used if using transformer classifier
    embed_weights: 'embedding/embed_weights.pt'
    gene_to_idx: 'embedding/word_to_idx.pt'
    freeze_embedding: True
training:
    batch_size: 32
    n_epochs: 10
    iters: 500
    lr: 0.0001
    weight_decay: 0.01
    dropout: 0.4
    label_weights: False
    known_labels: 0
    missing_values: False
validation:
    val_type: easy # easy, hard, random
    random_seed: 1